import { useState, useMemo } from 'react';
import {
  View,
  Text,
  ScrollView,
  Pressable,
  StyleSheet,
  ActivityIndicator,
  I18nManager,
} from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { useTheme } from '../theme/ThemeContext';
import { useLang } from '../theme/LanguageContext';
import { supabase } from '../lib/supabase';

const UI = {
  title: { ar: 'شروط الاستخدام', en: 'Terms of Use' },
  head_sub: { ar: 'يرجى قراءة الشروط كاملةً والموافقة عليها للمتابعة', en: 'Please read the full terms and accept them to continue' },
  intro: { ar: 'مرحباً بك في ميزان. قبل البدء، يرجى قراءة ما يلي والموافقة عليه.', en: 'Welcome to Mizan. Before you begin, please read and accept the following.' },
  end_hint: { ar: '— نهاية الشروط —', en: '— End of terms —' },
  agree: { ar: 'قرأت الشروط وأوافق عليها', en: 'I have read and agree to the terms' },
  scroll_hint: { ar: 'مرّر للأسفل لقراءة الشروط كاملةً', en: 'Scroll down to read the full terms' },
  continue_btn: { ar: 'متابعة', en: 'Continue' },
};

const SECTIONS = [
  {
    h: { ar: '١. طبيعة الخدمة', en: '1. Nature of the service' },
    p: {
      ar: 'ميزان أداة توعية استرشادية تقدّم معلومات وإرشادات عامّة ذات طابع توعوي بحت، بهدف تقريب فهم الإجراءات للمستخدم. ميزان ليس جهة حكومية أو رسمية، وليس مكتباً للمحاماة أو الاستشارات، ولا يمثّل أي جهة رسمية أو ينوب عنها.',
      en: 'Mizan is an awareness guidance tool that provides general, purely awareness-oriented information and guidance to help the user understand procedures. Mizan is not a government or official entity, nor a law or consulting firm, and does not represent or act on behalf of any official authority.',
    },
  },
  {
    h: { ar: '٢. المحتوى مولّد بالذكاء الاصطناعي', en: '2. Content is AI-generated' },
    p: {
      ar: 'تُولَّد ردود ميزان عبر أنظمة ذكاء اصطناعي. ورغم سعيه للدقّة، فإنّ هذه الأنظمة قد تُخطئ أو تقدّم معلومات غير دقيقة أو غير مكتملة أو غير محدّثة. لذا يجب التعامل مع كل ردّ باعتباره معلومة استرشادية أوّلية تحتاج تحقّقاً، لا حقيقة نهائية.',
      en: 'Mizan\u2019s responses are generated by AI systems. Despite striving for accuracy, these systems may err or provide inaccurate, incomplete, or outdated information. Each response should therefore be treated as preliminary guidance that needs verification, not a final fact.',
    },
  },
  {
    h: { ar: '٣. لا يقدّم استشارة ولا رأياً ملزماً', en: '3. No advice or binding opinion' },
    p: {
      ar: 'المحتوى المقدّم عبر ميزان لا يُعدّ استشارة قانونية أو مالية أو مهنية، ولا رأياً قانونيّاً، ولا توجيهاً ملزماً. ولا تنشأ بين المستخدم وميزان أي علاقة مهنية أو تعاقدية من أي نوع.',
      en: 'Content provided through Mizan is not legal, financial, or professional advice, nor a legal opinion, nor binding guidance. No professional or contractual relationship of any kind arises between the user and Mizan.',
    },
  },
  {
    h: { ar: '٤. لا ضمان للدقّة أو الاكتمال', en: '4. No guarantee of accuracy or completeness' },
    p: {
      ar: 'تُقدَّم المعلومات «كما هي» دون أي ضمان لدقّتها أو اكتمالها أو حداثتها. وقد تتغيّر الأنظمة والإجراءات والرسوم والمُدد في أي وقت، ولا يتحمّل ميزان مسؤولية أي معلومة أصبحت غير دقيقة أو متجاوزة.',
      en: 'Information is provided "as is" without any guarantee of its accuracy, completeness, or timeliness. Regulations, procedures, fees, and timeframes may change at any time, and Mizan bears no responsibility for any information that has become inaccurate or outdated.',
    },
  },
  {
    h: { ar: '٥. مسؤولية المستخدم في التحقّق', en: '5. The user\u2019s responsibility to verify' },
    p: {
      ar: 'يقع على المستخدم وحده مسؤولية التحقّق من أي معلومة من مصدرها الرسمي المختصّ قبل اتّخاذ أي قرار أو إجراء. وأي اعتماد على محتوى ميزان يكون على مسؤولية المستخدم الخاصّة.',
      en: 'The user alone is responsible for verifying any information from its competent official source before making any decision or taking any action. Any reliance on Mizan\u2019s content is at the user\u2019s own responsibility.',
    },
  },
  {
    h: { ar: '٦. إخلاء المسؤولية', en: '6. Disclaimer of liability' },
    p: {
      ar: 'لا يتحمّل ميزان ولا القائمون عليه أي مسؤولية عن أي ضرر مباشر أو غير مباشر، أو خسارة، أو نتيجة، تنشأ عن استخدام التطبيق أو الاعتماد على محتواه، أو عن أي خطأ في المحتوى المولّد آليّاً، إلى الحدّ الذي يسمح به النظام.',
      en: 'Neither Mizan nor those operating it bear any responsibility for any direct or indirect damage, loss, or outcome arising from use of the app or reliance on its content, or from any error in automatically generated content, to the extent permitted by law.',
    },
  },
  {
    h: { ar: '٧. الخصوصية', en: '7. Privacy' },
    p: {
      ar: 'يعالج ميزان الحدّ الأدنى من البيانات اللازمة لتشغيل الحساب، ويلتزم بنظام حماية البيانات الشخصية. للاطّلاع على التفاصيل، راجع سياسة الخصوصية داخل التطبيق.',
      en: 'Mizan processes the minimum data needed to run the account and complies with the Personal Data Protection Law. For details, see the Privacy Policy within the app.',
    },
  },
  {
    h: { ar: '٨. الموافقة', en: '8. Consent' },
    p: {
      ar: 'باستخدامك ميزان، تقرّ بأنّك قرأت هذه الشروط وفهمتها ووافقت عليها بالكامل.',
      en: 'By using Mizan, you acknowledge that you have read, understood, and fully agreed to these terms.',
    },
  },
];

export default function TermsScreen() {
  const insets = useSafeAreaInsets();
  const router = useRouter();
  const { colors } = useTheme();
  const { lang } = useLang();
  const styles = useMemo(() => makeStyles(colors), [colors]);
  const writingDir = I18nManager.isRTL ? 'rtl' : 'ltr';
  const L = (obj) => (obj && obj[lang]) || (obj && obj.ar) || '';
  const [reachedEnd, setReachedEnd] = useState(false);
  const [checked, setChecked] = useState(false);
  const [busy, setBusy] = useState(false);

  const onScroll = (e) => {
    const { layoutMeasurement, contentOffset, contentSize } = e.nativeEvent;
    if (layoutMeasurement.height + contentOffset.y >= contentSize.height - 40) {
      setReachedEnd(true);
    }
  };

  async function accept() {
    if (!checked || busy) return;
    setBusy(true);
    try {
      const { data: sess } = await supabase.auth.getSession();
      const uid = sess?.session?.user?.id;
      if (uid) {
        await supabase
          .from('profiles')
          .update({ terms_accepted_at: new Date().toISOString() })
          .eq('id', uid);
      }
    } catch (_) { /* تجاهل، نكمل */ }
    setBusy(false);
    router.replace('/(tabs)');
  }

  return (
    <View style={styles.root}>
      <StatusBar style="light" />
      <LinearGradient
        colors={[colors.emerald, colors.emeraldDeep]}
        start={{ x: 0, y: 0 }}
        end={{ x: 1, y: 1 }}
        style={[styles.head, { paddingTop: insets.top + 18 }]}
      >
        <Text style={[styles.headTitle, { writingDirection: writingDir }]}>{L(UI.title)}</Text>
        <Text style={[styles.headSub, { writingDirection: writingDir }]}>
          {L(UI.head_sub)}
        </Text>
      </LinearGradient>

      <ScrollView
        contentContainerStyle={styles.body}
        showsVerticalScrollIndicator
        onScroll={onScroll}
        scrollEventThrottle={80}
      >
        <Text style={[styles.intro, { writingDirection: writingDir }]}>
          {L(UI.intro)}
        </Text>
        {SECTIONS.map((s, i) => (
          <View key={i} style={styles.section}>
            <Text style={[styles.h, { writingDirection: writingDir }]}>{L(s.h)}</Text>
            <Text style={[styles.p, { writingDirection: writingDir }]}>{L(s.p)}</Text>
          </View>
        ))}
        <Text style={[styles.endHint, { writingDirection: writingDir }]}>{L(UI.end_hint)}</Text>
      </ScrollView>

      <View style={[styles.footer, { paddingBottom: insets.bottom + 14 }]}>
        <Pressable
          style={styles.checkRow}
          onPress={() => reachedEnd && setChecked((v) => !v)}
          disabled={!reachedEnd}
        >
          <View style={[styles.box, checked && styles.boxOn, !reachedEnd && styles.boxDim]}>
            {checked ? <Ionicons name="checkmark" size={16} color="#FFFFFF" /> : null}
          </View>
          <Text style={[styles.checkText, { writingDirection: writingDir }, !reachedEnd && styles.dimText]}>
            {reachedEnd ? L(UI.agree) : L(UI.scroll_hint)}
          </Text>
        </Pressable>

        <Pressable
          style={[styles.btn, (!checked || busy) && styles.btnDim]}
          onPress={accept}
          disabled={!checked || busy}
        >
          {busy ? (
            <ActivityIndicator color="#FFFFFF" />
          ) : (
            <Text style={styles.btnText}>{L(UI.continue_btn)}</Text>
          )}
        </Pressable>
      </View>
    </View>
  );
}

const makeStyles = (colors) => StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  head: {
    paddingHorizontal: 20,
    paddingBottom: 20,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  headTitle: { fontFamily: 'Cairo_700Bold', fontSize: 21, color: '#FFFFFF' },
  headSub: { fontFamily: 'Tajawal_500Medium', fontSize: 12.5, color: 'rgba(255,255,255,0.8)', marginTop: 5, lineHeight: 20 },
  body: { padding: 18, paddingBottom: 30 },
  intro: { fontFamily: 'Tajawal_500Medium', fontSize: 14, color: colors.textBody, lineHeight: 25, marginBottom: 16 },
  section: { marginBottom: 16 },
  h: { fontFamily: 'Cairo_700Bold', fontSize: 15, color: colors.emerald, marginBottom: 7 },
  p: { fontFamily: 'Tajawal_400Regular', fontSize: 13.5, color: colors.textBody, lineHeight: 24 },
  endHint: { fontFamily: 'Tajawal_500Medium', fontSize: 12, color: colors.muted, textAlign: 'center', marginTop: 8 },
  footer: {
    paddingHorizontal: 18,
    paddingTop: 14,
    backgroundColor: colors.card,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  checkRow: { flexDirection: 'row', alignItems: 'center', gap: 11, marginBottom: 14 },
  box: {
    width: 24,
    height: 24,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: colors.emerald,
    alignItems: 'center',
    justifyContent: 'center',
  },
  boxOn: { backgroundColor: colors.emerald },
  boxDim: { borderColor: colors.muted },
  checkText: { flex: 1, fontFamily: 'Tajawal_500Medium', fontSize: 13.5, color: colors.textDark },
  dimText: { color: colors.muted },
  btn: {
    height: 52,
    borderRadius: 15,
    backgroundColor: colors.emerald,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnDim: { backgroundColor: colors.muted, opacity: 0.5 },
  btnText: { fontFamily: 'Cairo_700Bold', fontSize: 16, color: '#FFFFFF' },
});
